name: Deploy Azure Function App

on:
  push:
    branches:
      - main  # or any branch you want to trigger the action on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Set up Python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Your Function App is on Python 3.11

    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Make sure to set this secret in your GitHub repo

    - name: 'Deploy to Azure Function App'
      uses: azure/functions-action@v1
      with:
        app-name: 'pastpaperupload'  # Your function app name
        package: '.'  # Deploy the current directory
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}  # Set this in your repo
